### ISSUE TITLE
AntiHunger Problem Floods Minecraft log

### ISSUE THREAD

**Issue by ENDvious** [BleachDrinker420/BleachHack#253]
Per game tick, Minecraft writes a to the log:

Jun. 18, 2021 7:00:55 P.M. com.google.common.eventbus.EventBus$LoggingHandler handleException
SEVERE: Exception thrown by subscriber method onSendPacket(bleach.hack.event.events.EventSendPacket) on subscriber bleach.hack.module.mods.AntiHunger@2c1ee7be when dispatching event: bleach.hack.event.events.EventSendPacket@122c3b77
java.lang.RuntimeException: Error reflecting field: onGround/field_12891 @class_2829
	at bleach.hack.util.FabricReflect.getField(FabricReflect.java:56)
	at bleach.hack.util.FabricReflect.writeField(FabricReflect.java:115)
	at bleach.hack.module.mods.AntiHunger.onSendPacket(AntiHunger.java:37)
	at jdk.internal.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraft.class_2535.handler$zlc000$send(class_2535.java:1073)
	at net.minecraft.class_2535.method_10752(class_2535.java)
	at net.minecraft.class_2535.method_10743(class_2535.java:172)
	at net.minecraft.class_634.method_2883(class_634.java:724)
	at net.minecraft.class_746.method_3136(class_746.java:273)
	at net.minecraft.class_746.method_5773(class_746.java:220)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_638.method_32124(class_638.java:199)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:195)
	at net.minecraft.class_310.method_1574(class_310.java:1752)

With the only difference being the classes it references

**Comment by BleachDrinker420** [comment]
what mc version are you using?

**Comment by ENDvious** [comment]
> 
> 
> what mc version are you using?
 1.17

**Comment by BleachDrinker420** [comment]
Fixed in https://github.com/BleachDrinker420/BleachHack/commit/cf304f070e8d9fd2cc0ce7e53af7cdc39215b255
