### ISSUE TITLE
[Bug] Doesn't work with Iris shader mod

### ISSUE THREAD

**Issue by DarkReaper231** [BleachDrinker420/BleachHack#280]
[14:40:28] [Render thread/WARN]: Method overwrite conflict for method_22920 in mixins.iris.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo, previously written by me.jellysquid.mods.sodium.mixin.features.buffer_builder.intrinsics.MixinBufferBuilder. Skipping method.
[14:40:28] [Render thread/FATAL]: Mixin apply failed bleachhack.mixins.json:MixinBufferBuilder -> net.minecraft.class_287: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("FIELD") on net/minecraft/class_287::redirect_colorFixed with priority 1000 cannot inject into net/minecraft/class_287::method_23919(FFFFFFFFFIIFFF)V merged by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo with priority 1000 [PREINJECT Applicator Phase -> bleachhack.mixins.json:MixinBufferBuilder -> Prepare Injections ->  -> redirect$bhp000$redirect_colorFixed(Lnet/minecraft/class_287;)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("FIELD") on net/minecraft/class_287::redirect_colorFixed with priority 1000 cannot inject into net/minecraft/class_287::method_23919(FFFFFFFFFIIFFF)V merged by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo with priority 1000 [PREINJECT Applicator Phase -> bleachhack.mixins.json:MixinBufferBuilder -> Prepare Injections ->  -> redirect$bhp000$redirect_colorFixed(Lnet/minecraft/class_287;)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at meteordevelopment.meteorclient.MixinPlugin$Transformer.transformClassBytes(MixinPlugin.java:96) [meteor-client-0.4.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) [fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
	at net.minecraft.class_289.<init>(class_289.java:19) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_289.<init>(class_289.java:23) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_289.<clinit>(class_289.java:11) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(RenderSystem.java:44) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:176) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[14:40:29] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[14:40:29] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[14:40:29] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[14:40:29] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[14:40:29] [Render thread/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[14:40:29] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:40:29] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[14:40:29] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:40:29] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[14:40:29] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[14:40:29] [Render thread/INFO]: [STDERR]: 	... 2 more
[14:40:29] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[14:40:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_6396.method_37123(class_6396.java:65)
[14:40:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_37274(class_310.java:2417)
[14:40:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_22681(class_310.java:2412)
[14:40:29] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:187)
[14:40:29] [Render thread/INFO]: [STDERR]: 	... 7 more

**Comment by nhtoTheMonke** [comment]
obama joe official
