### ISSUE TITLE
Crash when trying to open UI in Main Menu

### ISSUE THREAD

**Issue by pog5** [BleachDrinker420/BleachHack#390]
Trying to click on ClickGUI on the title sceren on the bottom, then clicking UI on the top, the game crashes.

```java
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_18456()" because "org.bleachhack.module.mods.UI.mc.field_1687" is null
	at org.bleachhack.module.mods.UI.getPlayerSize(UI.java:395)
	at org.bleachhack.gui.clickgui.window.UIWindow.getSize(UIWindow.java:46)
	at org.bleachhack.gui.clickgui.window.UIContainer.getRight(UIContainer.java:63)
	at org.bleachhack.gui.clickgui.window.UIContainer.lambda$updatePositions$0(UIContainer.java:31)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.bleachhack.gui.clickgui.window.UIContainer.updatePositions(UIContainer.java:28)
	at org.bleachhack.gui.clickgui.UIClickGuiScreen.method_25394(UIClickGuiScreen.java:52)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	```

**Comment by BleachDev** [comment]
Fixed in https://github.com/BleachDrinker420/BleachHack/commit/934b49302780b1f584e962cba6244ad0794e3b72
