### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Hyphoduck** [BleachDrinker420/BleachHack#405]
Minecraft keeps crashing

Latest log:

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at net.minecraft.class_384.<init>(class_384.java:10)
	at net.minecraft.class_377.<clinit>(class_377.java:27)
	at net.minecraft.class_378.<init>(class_378.java:48)
	at net.minecraft.class_310.<init>(class_310.java:527)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 16 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [bleachhack.mixins.json:MixinShader] from phase [DEFAULT] in config [bleachhack.mixins.json] from mod [bleachhack] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Redirect ctor invocation was not found in net/minecraft/class_5944::<init>(Lnet/minecraft/class_5912;Ljava/lang/String;Lnet/minecraft/class_293;)V [INJECT Applicator Phase -> bleachhack.mixins.json:MixinShader -> Apply Injections ->  -> Inject -> bleachhack.mixins.json:MixinShader->@Redirect::init_identifier(Ljava/lang/String;)Lnet/minecraft/class_2960; from mod bleachhack]
	at org.spongepowered.asm.mixin.injection.invoke.RedirectInjector.postInject(RedirectInjector.java:371)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:280)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[Lastest crash log.txt](https://github.com/BleachDrinker420/BleachHack/files/7739214/Lastest.crash.log.txt)

**Comment by BleachDev** [comment]
Doesn't happen without any mods, figure out which mod causes it or i'm closing this issue

**Comment by Jonas199233** [comment]
> Doesn't happen without any mods, figure out which mod causes it or i'm closing this issue

sorry i didnt know i had to remove fabric api
