### ISSUE TITLE
[Bug] NotebotStealer is broken

### ISSUE THREAD

**Issue by SolsticeSpectrum** [BleachDrinker420/BleachHack#449]
It just creates empty file without any notes. It says in chat: Saved Song As: notebot0.txt [0 Notes]

followed by errors in log:
```
[16:30:45] [Render thread/ERROR]: Exception thrown by subscriber method org.bleachhack.module.mods.NotebotStealer.onSoundPlay(org.bleachhack.event.events.EventSoundPlay$Normal) when dispatching event: org.bleachhack.event.events.EventSoundPlay$Normal
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1111.method_4772()" because "this.field_5444" is null
	at net.minecraft.class_1102.method_4782(class_1102.java:76) ~[client-intermediary.jar:?]
	at org.bleachhack.module.mods.NotebotStealer.onSoundPlay(NotebotStealer.java:73) ~[darkhack-5.1.jar:?]
	at org.bleachhack.eventbus.BleachSubscriber.callSubscriber(BleachSubscriber.java:62) ~[darkhack-5.1.jar:?]
	at org.bleachhack.eventbus.handler.InexactEventHandler.post(InexactEventHandler.java:53) ~[darkhack-5.1.jar:?]
	at org.bleachhack.eventbus.BleachEventBus.post(BleachEventBus.java:30) ~[darkhack-5.1.jar:?]
	at net.minecraft.class_1140.handler$zdh000$play(class_1140.java:619) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4854(class_1140.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_4873(class_1144.java:229) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_8486(class_638.java:443) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_8465(class_638.java:418) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11146(class_634.java:1569) ~[client-intermediary.jar:?]
	at net.minecraft.class_2767.method_11895(class_2767.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_2767.method_11054(class_2767.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
```

**Comment by luigi052005** [comment]
I have the same problem
